// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using XbyOpenApi.Core.Client.Models;
using XbyOpenApi.Core.Client.Two.Connections.All;
namespace XbyOpenApi.Core.Client.Two.Connections
{
  /// <summary>
  /// Builds and executes requests for operations under \2\connections
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class ConnectionsRequestBuilder : BaseRequestBuilder
  {
    /// <summary>The all property</summary>
    public global::XbyOpenApi.Core.Client.Two.Connections.All.AllRequestBuilder All
    {
      get => new global::XbyOpenApi.Core.Client.Two.Connections.All.AllRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Connections.ConnectionsRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public ConnectionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/connections{?connection%2Efields,endpoints,max_results*,pagination_token*,status*}", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Connections.ConnectionsRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public ConnectionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/connections{?connection%2Efields,endpoints,max_results*,pagination_token*,status*}", rawUrl)
    {
    }
    /// <summary>
    /// Returns active and historical streaming connections with disconnect reasons for the authenticated application.
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.Get2ConnectionsResponse"/></returns>
    /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
    /// <exception cref="global::XbyOpenApi.Core.Client.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public async Task<global::XbyOpenApi.Core.Client.Models.Get2ConnectionsResponse?> GetAsync(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Connections.ConnectionsRequestBuilder.ConnectionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#nullable restore
#else
    public async Task<global::XbyOpenApi.Core.Client.Models.Get2ConnectionsResponse> GetAsync(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Connections.ConnectionsRequestBuilder.ConnectionsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#endif
      var requestInfo = ToGetRequestInformation(requestConfiguration);
      var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::XbyOpenApi.Core.Client.Models.Error.CreateFromDiscriminatorValue },
            };
      return await RequestAdapter.SendAsync<global::XbyOpenApi.Core.Client.Models.Get2ConnectionsResponse>(requestInfo, global::XbyOpenApi.Core.Client.Models.Get2ConnectionsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
    }
    /// <summary>
    /// Returns active and historical streaming connections with disconnect reasons for the authenticated application.
    /// </summary>
    /// <returns>A <see cref="RequestInformation"/></returns>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Connections.ConnectionsRequestBuilder.ConnectionsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
    {
#nullable restore
#else
    public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Connections.ConnectionsRequestBuilder.ConnectionsRequestBuilderGetQueryParameters>> requestConfiguration = default)
    {
#endif
      var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
      requestInfo.Configure(requestConfiguration);
      requestInfo.Headers.TryAdd("Accept", "application/json");
      return requestInfo;
    }
    /// <summary>
    /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Two.Connections.ConnectionsRequestBuilder"/></returns>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    public global::XbyOpenApi.Core.Client.Two.Connections.ConnectionsRequestBuilder WithUrl(string rawUrl)
    {
      return new global::XbyOpenApi.Core.Client.Two.Connections.ConnectionsRequestBuilder(rawUrl, RequestAdapter);
    }
    /// <summary>
    /// Returns active and historical streaming connections with disconnect reasons for the authenticated application.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConnectionsRequestBuilderGetQueryParameters
    {
      /// <summary>A comma separated list of Connection fields to display.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      [QueryParameter("connection%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Connections.GetConnectionFieldsQueryParameterType[]? ConnectionFields { get; set; }
#nullable restore
#else
      [QueryParameter("connection%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Connections.GetConnectionFieldsQueryParameterType[] ConnectionFields { get; set; }
#endif
      /// <summary>Filter by streaming endpoint. Specify one or more endpoint names to filter results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      [QueryParameter("endpoints")]
      public global::XbyOpenApi.Core.Client.Two.Connections.GetEndpointsQueryParameterType[]? Endpoints { get; set; }
#nullable restore
#else
      [QueryParameter("endpoints")]
      public global::XbyOpenApi.Core.Client.Two.Connections.GetEndpointsQueryParameterType[] Endpoints { get; set; }
#endif
      /// <summary>The maximum number of results to return per page.</summary>
      [QueryParameter("max_results")]
      public int? MaxResults { get; set; }
      /// <summary>Token for paginating through results. Use the value from &apos;next_token&apos; in the previous response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      [QueryParameter("pagination_token")]
      public string? PaginationToken { get; set; }
#nullable restore
#else
      [QueryParameter("pagination_token")]
      public string PaginationToken { get; set; }
#endif
      /// <summary>Filter by connection status. Use &apos;active&apos; for current connections, &apos;inactive&apos; for historical/disconnected connections, or &apos;all&apos; for both.</summary>
      [QueryParameter("status")]
      public global::XbyOpenApi.Core.Client.Two.Connections.GetStatusQueryParameterType? Status { get; set; }
    }
  }
}
#pragma warning restore CS0618
