// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using XbyOpenApi.Core.Client.Models;
using XbyOpenApi.Core.Client.Two.Compliance.Jobs.Item;
namespace XbyOpenApi.Core.Client.Two.Compliance.Jobs
{
  /// <summary>
  /// Builds and executes requests for operations under \2\compliance\jobs
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class JobsRequestBuilder : BaseRequestBuilder
  {
    /// <summary>Gets an item from the XbyOpenApi.Core.Client.Two.compliance.jobs.item collection</summary>
    /// <param name="position">The ID of the Compliance Job to retrieve.</param>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Two.Compliance.Jobs.Item.JobsItemRequestBuilder"/></returns>
    public global::XbyOpenApi.Core.Client.Two.Compliance.Jobs.Item.JobsItemRequestBuilder this[string position]
    {
      get
      {
        var urlTplParams = new Dictionary<string, object>(PathParameters);
        urlTplParams.Add("id", position);
        return new global::XbyOpenApi.Core.Client.Two.Compliance.Jobs.Item.JobsItemRequestBuilder(urlTplParams, RequestAdapter);
      }
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Compliance.Jobs.JobsRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public JobsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/compliance/jobs?type={type}{&compliance_job%2Efields,status*}", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Compliance.Jobs.JobsRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public JobsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/compliance/jobs?type={type}{&compliance_job%2Efields,status*}", rawUrl)
    {
    }
    /// <summary>
    /// Retrieves a list of Compliance Jobs filtered by job type and optional status.
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.Get2ComplianceJobsResponse"/></returns>
    /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
    /// <exception cref="global::XbyOpenApi.Core.Client.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public async Task<global::XbyOpenApi.Core.Client.Models.Get2ComplianceJobsResponse?> GetAsync(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Compliance.Jobs.JobsRequestBuilder.JobsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#nullable restore
#else
    public async Task<global::XbyOpenApi.Core.Client.Models.Get2ComplianceJobsResponse> GetAsync(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Compliance.Jobs.JobsRequestBuilder.JobsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#endif
      var requestInfo = ToGetRequestInformation(requestConfiguration);
      var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::XbyOpenApi.Core.Client.Models.Error.CreateFromDiscriminatorValue },
            };
      return await RequestAdapter.SendAsync<global::XbyOpenApi.Core.Client.Models.Get2ComplianceJobsResponse>(requestInfo, global::XbyOpenApi.Core.Client.Models.Get2ComplianceJobsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
    }
    /// <summary>
    /// Creates a new Compliance Job for the specified job type.
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.CreateComplianceJobResponse"/></returns>
    /// <param name="body">A request to create a new batch compliance job.</param>
    /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
    /// <exception cref="global::XbyOpenApi.Core.Client.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public async Task<global::XbyOpenApi.Core.Client.Models.CreateComplianceJobResponse?> PostAsync(global::XbyOpenApi.Core.Client.Models.CreateComplianceJobRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#nullable restore
#else
    public async Task<global::XbyOpenApi.Core.Client.Models.CreateComplianceJobResponse> PostAsync(global::XbyOpenApi.Core.Client.Models.CreateComplianceJobRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#endif
      if (ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
      var requestInfo = ToPostRequestInformation(body, requestConfiguration);
      var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::XbyOpenApi.Core.Client.Models.Error.CreateFromDiscriminatorValue },
            };
      return await RequestAdapter.SendAsync<global::XbyOpenApi.Core.Client.Models.CreateComplianceJobResponse>(requestInfo, global::XbyOpenApi.Core.Client.Models.CreateComplianceJobResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
    }
    /// <summary>
    /// Retrieves a list of Compliance Jobs filtered by job type and optional status.
    /// </summary>
    /// <returns>A <see cref="RequestInformation"/></returns>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Compliance.Jobs.JobsRequestBuilder.JobsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
    {
#nullable restore
#else
    public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Compliance.Jobs.JobsRequestBuilder.JobsRequestBuilderGetQueryParameters>> requestConfiguration = default)
    {
#endif
      var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
      requestInfo.Configure(requestConfiguration);
      requestInfo.Headers.TryAdd("Accept", "application/json");
      return requestInfo;
    }
    /// <summary>
    /// Creates a new Compliance Job for the specified job type.
    /// </summary>
    /// <returns>A <see cref="RequestInformation"/></returns>
    /// <param name="body">A request to create a new batch compliance job.</param>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public RequestInformation ToPostRequestInformation(global::XbyOpenApi.Core.Client.Models.CreateComplianceJobRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
    {
#nullable restore
#else
    public RequestInformation ToPostRequestInformation(global::XbyOpenApi.Core.Client.Models.CreateComplianceJobRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
    {
#endif
      if (ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
      var requestInfo = new RequestInformation(Method.POST, "{+baseurl}/2/compliance/jobs", PathParameters);
      requestInfo.Configure(requestConfiguration);
      requestInfo.Headers.TryAdd("Accept", "application/json");
      requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
      return requestInfo;
    }
    /// <summary>
    /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Two.Compliance.Jobs.JobsRequestBuilder"/></returns>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    public global::XbyOpenApi.Core.Client.Two.Compliance.Jobs.JobsRequestBuilder WithUrl(string rawUrl)
    {
      return new global::XbyOpenApi.Core.Client.Two.Compliance.Jobs.JobsRequestBuilder(rawUrl, RequestAdapter);
    }
    /// <summary>
    /// Retrieves a list of Compliance Jobs filtered by job type and optional status.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class JobsRequestBuilderGetQueryParameters
    {
      /// <summary>A comma separated list of ComplianceJob fields to display.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      [QueryParameter("compliance_job%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Compliance.Jobs.GetCompliance_jobFieldsQueryParameterType[]? ComplianceJobFields { get; set; }
#nullable restore
#else
      [QueryParameter("compliance_job%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Compliance.Jobs.GetCompliance_jobFieldsQueryParameterType[] ComplianceJobFields { get; set; }
#endif
      /// <summary>Status of Compliance Job to list.</summary>
      [QueryParameter("status")]
      public global::XbyOpenApi.Core.Client.Two.Compliance.Jobs.GetStatusQueryParameterType? Status { get; set; }
      /// <summary>Type of Compliance Job to list.</summary>
      [QueryParameter("type")]
      public global::XbyOpenApi.Core.Client.Two.Compliance.Jobs.GetTypeQueryParameterType? Type { get; set; }
    }
  }
}
#pragma warning restore CS0618
