// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using XbyOpenApi.Core.Client.Two.Account_activity;
using XbyOpenApi.Core.Client.Two.Activity;
using XbyOpenApi.Core.Client.Two.Chat;
using XbyOpenApi.Core.Client.Two.Communities;
using XbyOpenApi.Core.Client.Two.Compliance;
using XbyOpenApi.Core.Client.Two.Connections;
using XbyOpenApi.Core.Client.Two.Dm_conversations;
using XbyOpenApi.Core.Client.Two.Dm_events;
using XbyOpenApi.Core.Client.Two.Evaluate_note;
using XbyOpenApi.Core.Client.Two.Insights;
using XbyOpenApi.Core.Client.Two.Likes;
using XbyOpenApi.Core.Client.Two.Lists;
using XbyOpenApi.Core.Client.Two.Media;
using XbyOpenApi.Core.Client.Two.News;
using XbyOpenApi.Core.Client.Two.Notes;
using XbyOpenApi.Core.Client.Two.OpenapiJson;
using XbyOpenApi.Core.Client.Two.Spaces;
using XbyOpenApi.Core.Client.Two.Trends;
using XbyOpenApi.Core.Client.Two.Tweets;
using XbyOpenApi.Core.Client.Two.Usage;
using XbyOpenApi.Core.Client.Two.Users;
using XbyOpenApi.Core.Client.Two.Webhooks;
namespace XbyOpenApi.Core.Client.Two
{
  /// <summary>
  /// Builds and executes requests for operations under \2
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class TwoRequestBuilder : BaseRequestBuilder
  {
    /// <summary>The account_activity property</summary>
    public global::XbyOpenApi.Core.Client.Two.Account_activity.Account_activityRequestBuilder Account_activity
    {
      get => new global::XbyOpenApi.Core.Client.Two.Account_activity.Account_activityRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The activity property</summary>
    public global::XbyOpenApi.Core.Client.Two.Activity.ActivityRequestBuilder Activity
    {
      get => new global::XbyOpenApi.Core.Client.Two.Activity.ActivityRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The chat property</summary>
    public global::XbyOpenApi.Core.Client.Two.Chat.ChatRequestBuilder Chat
    {
      get => new global::XbyOpenApi.Core.Client.Two.Chat.ChatRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The communities property</summary>
    public global::XbyOpenApi.Core.Client.Two.Communities.CommunitiesRequestBuilder Communities
    {
      get => new global::XbyOpenApi.Core.Client.Two.Communities.CommunitiesRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The compliance property</summary>
    public global::XbyOpenApi.Core.Client.Two.Compliance.ComplianceRequestBuilder Compliance
    {
      get => new global::XbyOpenApi.Core.Client.Two.Compliance.ComplianceRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The connections property</summary>
    public global::XbyOpenApi.Core.Client.Two.Connections.ConnectionsRequestBuilder Connections
    {
      get => new global::XbyOpenApi.Core.Client.Two.Connections.ConnectionsRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The dm_conversations property</summary>
    public global::XbyOpenApi.Core.Client.Two.Dm_conversations.Dm_conversationsRequestBuilder Dm_conversations
    {
      get => new global::XbyOpenApi.Core.Client.Two.Dm_conversations.Dm_conversationsRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The dm_events property</summary>
    public global::XbyOpenApi.Core.Client.Two.Dm_events.Dm_eventsRequestBuilder Dm_events
    {
      get => new global::XbyOpenApi.Core.Client.Two.Dm_events.Dm_eventsRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The evaluate_note property</summary>
    public global::XbyOpenApi.Core.Client.Two.Evaluate_note.Evaluate_noteRequestBuilder Evaluate_note
    {
      get => new global::XbyOpenApi.Core.Client.Two.Evaluate_note.Evaluate_noteRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The insights property</summary>
    public global::XbyOpenApi.Core.Client.Two.Insights.InsightsRequestBuilder Insights
    {
      get => new global::XbyOpenApi.Core.Client.Two.Insights.InsightsRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The likes property</summary>
    public global::XbyOpenApi.Core.Client.Two.Likes.LikesRequestBuilder Likes
    {
      get => new global::XbyOpenApi.Core.Client.Two.Likes.LikesRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The lists property</summary>
    public global::XbyOpenApi.Core.Client.Two.Lists.ListsRequestBuilder Lists
    {
      get => new global::XbyOpenApi.Core.Client.Two.Lists.ListsRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The media property</summary>
    public global::XbyOpenApi.Core.Client.Two.Media.MediaRequestBuilder Media
    {
      get => new global::XbyOpenApi.Core.Client.Two.Media.MediaRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The news property</summary>
    public global::XbyOpenApi.Core.Client.Two.News.NewsRequestBuilder News
    {
      get => new global::XbyOpenApi.Core.Client.Two.News.NewsRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The notes property</summary>
    public global::XbyOpenApi.Core.Client.Two.Notes.NotesRequestBuilder Notes
    {
      get => new global::XbyOpenApi.Core.Client.Two.Notes.NotesRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The openapiJson property</summary>
    public global::XbyOpenApi.Core.Client.Two.OpenapiJson.OpenapiJsonRequestBuilder OpenapiJson
    {
      get => new global::XbyOpenApi.Core.Client.Two.OpenapiJson.OpenapiJsonRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The spaces property</summary>
    public global::XbyOpenApi.Core.Client.Two.Spaces.SpacesRequestBuilder Spaces
    {
      get => new global::XbyOpenApi.Core.Client.Two.Spaces.SpacesRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The trends property</summary>
    public global::XbyOpenApi.Core.Client.Two.Trends.TrendsRequestBuilder Trends
    {
      get => new global::XbyOpenApi.Core.Client.Two.Trends.TrendsRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The tweets property</summary>
    public global::XbyOpenApi.Core.Client.Two.Tweets.TweetsRequestBuilder Tweets
    {
      get => new global::XbyOpenApi.Core.Client.Two.Tweets.TweetsRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The usage property</summary>
    public global::XbyOpenApi.Core.Client.Two.Usage.UsageRequestBuilder Usage
    {
      get => new global::XbyOpenApi.Core.Client.Two.Usage.UsageRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The users property</summary>
    public global::XbyOpenApi.Core.Client.Two.Users.UsersRequestBuilder Users
    {
      get => new global::XbyOpenApi.Core.Client.Two.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The webhooks property</summary>
    public global::XbyOpenApi.Core.Client.Two.Webhooks.WebhooksRequestBuilder Webhooks
    {
      get => new global::XbyOpenApi.Core.Client.Two.Webhooks.WebhooksRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.TwoRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public TwoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.TwoRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public TwoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2", rawUrl)
    {
    }
  }
}
#pragma warning restore CS0618
