// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using XbyOpenApi.Core.Client.Two.Chat.Media.Upload.Item.Append;
using XbyOpenApi.Core.Client.Two.Chat.Media.Upload.Item.Finalize;
namespace XbyOpenApi.Core.Client.Two.Chat.Media.Upload.Item
{
  /// <summary>
  /// Builds and executes requests for operations under \2\chat\media\upload\{id}
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class UploadItemRequestBuilder : BaseRequestBuilder
  {
    /// <summary>The append property</summary>
    public global::XbyOpenApi.Core.Client.Two.Chat.Media.Upload.Item.Append.AppendRequestBuilder Append
    {
      get => new global::XbyOpenApi.Core.Client.Two.Chat.Media.Upload.Item.Append.AppendRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The finalize property</summary>
    public global::XbyOpenApi.Core.Client.Two.Chat.Media.Upload.Item.Finalize.FinalizeRequestBuilder Finalize
    {
      get => new global::XbyOpenApi.Core.Client.Two.Chat.Media.Upload.Item.Finalize.FinalizeRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Chat.Media.Upload.Item.UploadItemRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public UploadItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/chat/media/upload/{id}", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Chat.Media.Upload.Item.UploadItemRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public UploadItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/chat/media/upload/{id}", rawUrl)
    {
    }
  }
}
#pragma warning restore CS0618
