// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using XbyOpenApi.Core.Client.Models;
using XbyOpenApi.Core.Client.Two.Media.Analytics;
using XbyOpenApi.Core.Client.Two.Media.Item;
using XbyOpenApi.Core.Client.Two.Media.Metadata;
using XbyOpenApi.Core.Client.Two.Media.Subtitles;
using XbyOpenApi.Core.Client.Two.Media.Upload;
namespace XbyOpenApi.Core.Client.Two.Media
{
  /// <summary>
  /// Builds and executes requests for operations under \2\media
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class MediaRequestBuilder : BaseRequestBuilder
  {
    /// <summary>The analytics property</summary>
    public global::XbyOpenApi.Core.Client.Two.Media.Analytics.AnalyticsRequestBuilder Analytics
    {
      get => new global::XbyOpenApi.Core.Client.Two.Media.Analytics.AnalyticsRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The metadata property</summary>
    public global::XbyOpenApi.Core.Client.Two.Media.Metadata.MetadataRequestBuilder Metadata
    {
      get => new global::XbyOpenApi.Core.Client.Two.Media.Metadata.MetadataRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The subtitles property</summary>
    public global::XbyOpenApi.Core.Client.Two.Media.Subtitles.SubtitlesRequestBuilder Subtitles
    {
      get => new global::XbyOpenApi.Core.Client.Two.Media.Subtitles.SubtitlesRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The upload property</summary>
    public global::XbyOpenApi.Core.Client.Two.Media.Upload.UploadRequestBuilder Upload
    {
      get => new global::XbyOpenApi.Core.Client.Two.Media.Upload.UploadRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>Gets an item from the XbyOpenApi.Core.Client.Two.media.item collection</summary>
    /// <param name="position">A single Media Key.</param>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Two.Media.Item.WithMedia_keyItemRequestBuilder"/></returns>
    public global::XbyOpenApi.Core.Client.Two.Media.Item.WithMedia_keyItemRequestBuilder this[string position]
    {
      get
      {
        var urlTplParams = new Dictionary<string, object>(PathParameters);
        urlTplParams.Add("media_key", position);
        return new global::XbyOpenApi.Core.Client.Two.Media.Item.WithMedia_keyItemRequestBuilder(urlTplParams, RequestAdapter);
      }
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Media.MediaRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public MediaRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/media?media_keys={media_keys}{&media%2Efields}", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Media.MediaRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public MediaRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/media?media_keys={media_keys}{&media%2Efields}", rawUrl)
    {
    }
    /// <summary>
    /// Retrieves details of Media files by their media keys.
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.Get2MediaResponse"/></returns>
    /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
    /// <exception cref="global::XbyOpenApi.Core.Client.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public async Task<global::XbyOpenApi.Core.Client.Models.Get2MediaResponse?> GetAsync(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Media.MediaRequestBuilder.MediaRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#nullable restore
#else
    public async Task<global::XbyOpenApi.Core.Client.Models.Get2MediaResponse> GetAsync(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Media.MediaRequestBuilder.MediaRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#endif
      var requestInfo = ToGetRequestInformation(requestConfiguration);
      var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::XbyOpenApi.Core.Client.Models.Error.CreateFromDiscriminatorValue },
            };
      return await RequestAdapter.SendAsync<global::XbyOpenApi.Core.Client.Models.Get2MediaResponse>(requestInfo, global::XbyOpenApi.Core.Client.Models.Get2MediaResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
    }
    /// <summary>
    /// Retrieves details of Media files by their media keys.
    /// </summary>
    /// <returns>A <see cref="RequestInformation"/></returns>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Media.MediaRequestBuilder.MediaRequestBuilderGetQueryParameters>>? requestConfiguration = default)
    {
#nullable restore
#else
    public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Media.MediaRequestBuilder.MediaRequestBuilderGetQueryParameters>> requestConfiguration = default)
    {
#endif
      var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
      requestInfo.Configure(requestConfiguration);
      requestInfo.Headers.TryAdd("Accept", "application/json");
      return requestInfo;
    }
    /// <summary>
    /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Two.Media.MediaRequestBuilder"/></returns>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    public global::XbyOpenApi.Core.Client.Two.Media.MediaRequestBuilder WithUrl(string rawUrl)
    {
      return new global::XbyOpenApi.Core.Client.Two.Media.MediaRequestBuilder(rawUrl, RequestAdapter);
    }
    /// <summary>
    /// Retrieves details of Media files by their media keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MediaRequestBuilderGetQueryParameters
    {
      /// <summary>A comma separated list of Media fields to display.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      [QueryParameter("media%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Media.GetMediaFieldsQueryParameterType[]? MediaFields { get; set; }
#nullable restore
#else
      [QueryParameter("media%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Media.GetMediaFieldsQueryParameterType[] MediaFields { get; set; }
#endif
      /// <summary>A comma separated list of Media Keys. Up to 100 are allowed in a single request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      [QueryParameter("media_keys")]
      public string[]? MediaKeys { get; set; }
#nullable restore
#else
      [QueryParameter("media_keys")]
      public string[] MediaKeys { get; set; }
#endif
    }
  }
}
#pragma warning restore CS0618
