// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using XbyOpenApi.Core.Client.Models;
using XbyOpenApi.Core.Client.Two.Users.Item.Bookmarks.Folders.Item;
namespace XbyOpenApi.Core.Client.Two.Users.Item.Bookmarks.Folders
{
  /// <summary>
  /// Builds and executes requests for operations under \2\users\{-id}\bookmarks\folders
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class FoldersRequestBuilder : BaseRequestBuilder
  {
    /// <summary>Gets an item from the XbyOpenApi.Core.Client.Two.users.item.bookmarks.folders.item collection</summary>
    /// <param name="position">The ID of the Bookmark Folder that the authenticated User is trying to fetch Posts for.</param>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Two.Users.Item.Bookmarks.Folders.Item.WithFolder_ItemRequestBuilder"/></returns>
    public global::XbyOpenApi.Core.Client.Two.Users.Item.Bookmarks.Folders.Item.WithFolder_ItemRequestBuilder this[string position]
    {
      get
      {
        var urlTplParams = new Dictionary<string, object>(PathParameters);
        urlTplParams.Add("folder_id", position);
        return new global::XbyOpenApi.Core.Client.Two.Users.Item.Bookmarks.Folders.Item.WithFolder_ItemRequestBuilder(urlTplParams, RequestAdapter);
      }
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Users.Item.Bookmarks.Folders.FoldersRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public FoldersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/users/{%2Did}/bookmarks/folders{?max_results*,pagination_token*}", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Users.Item.Bookmarks.Folders.FoldersRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public FoldersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/users/{%2Did}/bookmarks/folders{?max_results*,pagination_token*}", rawUrl)
    {
    }
    /// <summary>
    /// Retrieves a list of Bookmark folders created by the authenticated user.
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.BookmarkFoldersResponse"/></returns>
    /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
    /// <exception cref="global::XbyOpenApi.Core.Client.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public async Task<global::XbyOpenApi.Core.Client.Models.BookmarkFoldersResponse?> GetAsync(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Users.Item.Bookmarks.Folders.FoldersRequestBuilder.FoldersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#nullable restore
#else
    public async Task<global::XbyOpenApi.Core.Client.Models.BookmarkFoldersResponse> GetAsync(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Users.Item.Bookmarks.Folders.FoldersRequestBuilder.FoldersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#endif
      var requestInfo = ToGetRequestInformation(requestConfiguration);
      var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::XbyOpenApi.Core.Client.Models.Error.CreateFromDiscriminatorValue },
            };
      return await RequestAdapter.SendAsync<global::XbyOpenApi.Core.Client.Models.BookmarkFoldersResponse>(requestInfo, global::XbyOpenApi.Core.Client.Models.BookmarkFoldersResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
    }
    /// <summary>
    /// Retrieves a list of Bookmark folders created by the authenticated user.
    /// </summary>
    /// <returns>A <see cref="RequestInformation"/></returns>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Users.Item.Bookmarks.Folders.FoldersRequestBuilder.FoldersRequestBuilderGetQueryParameters>>? requestConfiguration = default)
    {
#nullable restore
#else
    public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Users.Item.Bookmarks.Folders.FoldersRequestBuilder.FoldersRequestBuilderGetQueryParameters>> requestConfiguration = default)
    {
#endif
      var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
      requestInfo.Configure(requestConfiguration);
      requestInfo.Headers.TryAdd("Accept", "application/json");
      return requestInfo;
    }
    /// <summary>
    /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Two.Users.Item.Bookmarks.Folders.FoldersRequestBuilder"/></returns>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    public global::XbyOpenApi.Core.Client.Two.Users.Item.Bookmarks.Folders.FoldersRequestBuilder WithUrl(string rawUrl)
    {
      return new global::XbyOpenApi.Core.Client.Two.Users.Item.Bookmarks.Folders.FoldersRequestBuilder(rawUrl, RequestAdapter);
    }
    /// <summary>
    /// Retrieves a list of Bookmark folders created by the authenticated user.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FoldersRequestBuilderGetQueryParameters
    {
      /// <summary>The maximum number of results.</summary>
      [QueryParameter("max_results")]
      public int? MaxResults { get; set; }
      /// <summary>This parameter is used to get the next &apos;page&apos; of results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      [QueryParameter("pagination_token")]
      public string? PaginationToken { get; set; }
#nullable restore
#else
      [QueryParameter("pagination_token")]
      public string PaginationToken { get; set; }
#endif
    }
  }
}
#pragma warning restore CS0618
