// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using XbyOpenApi.Core.Client.Two.Chat.Media.Item.Item;
namespace XbyOpenApi.Core.Client.Two.Chat.Media.Item
{
  /// <summary>
  /// Builds and executes requests for operations under \2\chat\media\{id}
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class MediaItemRequestBuilder : BaseRequestBuilder
  {
    /// <summary>Gets an item from the XbyOpenApi.Core.Client.Two.chat.media.item.item collection</summary>
    /// <param name="position">The media hash key returned from the upload initialize step.</param>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Two.Chat.Media.Item.Item.WithMedia_hash_keyItemRequestBuilder"/></returns>
    public global::XbyOpenApi.Core.Client.Two.Chat.Media.Item.Item.WithMedia_hash_keyItemRequestBuilder this[string position]
    {
      get
      {
        var urlTplParams = new Dictionary<string, object>(PathParameters);
        urlTplParams.Add("media_hash_key", position);
        return new global::XbyOpenApi.Core.Client.Two.Chat.Media.Item.Item.WithMedia_hash_keyItemRequestBuilder(urlTplParams, RequestAdapter);
      }
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Chat.Media.Item.MediaItemRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public MediaItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/chat/media/{id}", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Chat.Media.Item.MediaItemRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public MediaItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/chat/media/{id}", rawUrl)
    {
    }
  }
}
#pragma warning restore CS0618
