// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using XbyOpenApi.Core.Client.Two.Chat.Media.Upload.Initialize;
using XbyOpenApi.Core.Client.Two.Chat.Media.Upload.Item;
namespace XbyOpenApi.Core.Client.Two.Chat.Media.Upload
{
  /// <summary>
  /// Builds and executes requests for operations under \2\chat\media\upload
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class UploadRequestBuilder : BaseRequestBuilder
  {
    /// <summary>The initialize property</summary>
    public global::XbyOpenApi.Core.Client.Two.Chat.Media.Upload.Initialize.InitializeRequestBuilder Initialize
    {
      get => new global::XbyOpenApi.Core.Client.Two.Chat.Media.Upload.Initialize.InitializeRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>Gets an item from the XbyOpenApi.Core.Client.Two.chat.media.upload.item collection</summary>
    /// <param name="position">The session/resume id from initialize.</param>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Two.Chat.Media.Upload.Item.UploadItemRequestBuilder"/></returns>
    public global::XbyOpenApi.Core.Client.Two.Chat.Media.Upload.Item.UploadItemRequestBuilder this[string position]
    {
      get
      {
        var urlTplParams = new Dictionary<string, object>(PathParameters);
        urlTplParams.Add("id", position);
        return new global::XbyOpenApi.Core.Client.Two.Chat.Media.Upload.Item.UploadItemRequestBuilder(urlTplParams, RequestAdapter);
      }
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Chat.Media.Upload.UploadRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public UploadRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/chat/media/upload", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Chat.Media.Upload.UploadRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public UploadRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/chat/media/upload", rawUrl)
    {
    }
  }
}
#pragma warning restore CS0618
