//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XByOpenApi.Sample.WinForms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AuthorizationIsOAuth1 {
            get {
                return ((bool)(this["AuthorizationIsOAuth1"]));
            }
            set {
                this["AuthorizationIsOAuth1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OAuth1ConsumerAPIKey {
            get {
                return ((string)(this["OAuth1ConsumerAPIKey"]));
            }
            set {
                this["OAuth1ConsumerAPIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OAuth1PinBased {
            get {
                return ((bool)(this["OAuth1PinBased"]));
            }
            set {
                this["OAuth1PinBased"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost")]
        public string OAuth1RedirectUrl {
            get {
                return ((string)(this["OAuth1RedirectUrl"]));
            }
            set {
                this["OAuth1RedirectUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OAuth2ClientID {
            get {
                return ((string)(this["OAuth2ClientID"]));
            }
            set {
                this["OAuth2ClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost")]
        public string OAuth2RedirectUrl {
            get {
                return ((string)(this["OAuth2RedirectUrl"]));
            }
            set {
                this["OAuth2RedirectUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OAuth2PublicClient {
            get {
                return ((bool)(this["OAuth2PublicClient"]));
            }
            set {
                this["OAuth2PublicClient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OAuth2FetchRefreshToken {
            get {
                return ((bool)(this["OAuth2FetchRefreshToken"]));
            }
            set {
                this["OAuth2FetchRefreshToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OAuth2CodeChallengeMethodSHA256 {
            get {
                return ((bool)(this["OAuth2CodeChallengeMethodSHA256"]));
            }
            set {
                this["OAuth2CodeChallengeMethodSHA256"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingsWrittenByCurrentVersion {
            get {
                return ((bool)(this["SettingsWrittenByCurrentVersion"]));
            }
            set {
                this["SettingsWrittenByCurrentVersion"] = value;
            }
        }
    }
}
