// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using XbyOpenApi.Core.Client.Models;
using XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.Keys;
using XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.Members;
using XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.Messages;
using XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.Read;
using XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.Typing;
namespace XbyOpenApi.Core.Client.Two.Chat.Conversations.Item
{
  /// <summary>
  /// Builds and executes requests for operations under \2\chat\conversations\{id}
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class ConversationsItemRequestBuilder : BaseRequestBuilder
  {
    /// <summary>The keys property</summary>
    public global::XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.Keys.KeysRequestBuilder Keys
    {
      get => new global::XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.Keys.KeysRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The members property</summary>
    public global::XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.Members.MembersRequestBuilder Members
    {
      get => new global::XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.Members.MembersRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The messages property</summary>
    public global::XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.Messages.MessagesRequestBuilder Messages
    {
      get => new global::XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.Messages.MessagesRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The read property</summary>
    public global::XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.Read.ReadRequestBuilder Read
    {
      get => new global::XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.Read.ReadRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The typing property</summary>
    public global::XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.Typing.TypingRequestBuilder Typing
    {
      get => new global::XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.Typing.TypingRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.ConversationsItemRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public ConversationsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/chat/conversations/{id}{?chat_message_event%2Efields,max_results*,pagination_token*}", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.ConversationsItemRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public ConversationsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/chat/conversations/{id}{?chat_message_event%2Efields,max_results*,pagination_token*}", rawUrl)
    {
    }
    /// <summary>
    /// Retrieves messages and key change events for a specific Chat conversation with pagination support. For 1:1 conversations, provide the recipient&apos;s user ID; the server constructs the canonical conversation ID from the authenticated user and recipient.
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.ChatGetConversationResponse"/></returns>
    /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
    /// <exception cref="global::XbyOpenApi.Core.Client.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public async Task<global::XbyOpenApi.Core.Client.Models.ChatGetConversationResponse?> GetAsync(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.ConversationsItemRequestBuilder.ConversationsItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#nullable restore
#else
    public async Task<global::XbyOpenApi.Core.Client.Models.ChatGetConversationResponse> GetAsync(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.ConversationsItemRequestBuilder.ConversationsItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#endif
      var requestInfo = ToGetRequestInformation(requestConfiguration);
      var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::XbyOpenApi.Core.Client.Models.Error.CreateFromDiscriminatorValue },
            };
      return await RequestAdapter.SendAsync<global::XbyOpenApi.Core.Client.Models.ChatGetConversationResponse>(requestInfo, global::XbyOpenApi.Core.Client.Models.ChatGetConversationResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
    }
    /// <summary>
    /// Retrieves messages and key change events for a specific Chat conversation with pagination support. For 1:1 conversations, provide the recipient&apos;s user ID; the server constructs the canonical conversation ID from the authenticated user and recipient.
    /// </summary>
    /// <returns>A <see cref="RequestInformation"/></returns>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.ConversationsItemRequestBuilder.ConversationsItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
    {
#nullable restore
#else
    public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.ConversationsItemRequestBuilder.ConversationsItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
    {
#endif
      var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
      requestInfo.Configure(requestConfiguration);
      requestInfo.Headers.TryAdd("Accept", "application/json");
      return requestInfo;
    }
    /// <summary>
    /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.ConversationsItemRequestBuilder"/></returns>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    public global::XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.ConversationsItemRequestBuilder WithUrl(string rawUrl)
    {
      return new global::XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.ConversationsItemRequestBuilder(rawUrl, RequestAdapter);
    }
    /// <summary>
    /// Retrieves messages and key change events for a specific Chat conversation with pagination support. For 1:1 conversations, provide the recipient&apos;s user ID; the server constructs the canonical conversation ID from the authenticated user and recipient.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConversationsItemRequestBuilderGetQueryParameters
    {
      /// <summary>A comma separated list of ChatMessageEvent fields to display.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      [QueryParameter("chat_message_event%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.GetChat_message_eventFieldsQueryParameterType[]? ChatMessageEventFields { get; set; }
#nullable restore
#else
      [QueryParameter("chat_message_event%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Chat.Conversations.Item.GetChat_message_eventFieldsQueryParameterType[] ChatMessageEventFields { get; set; }
#endif
      /// <summary>Maximum number of message events to return.</summary>
      [QueryParameter("max_results")]
      public int? MaxResults { get; set; }
      /// <summary>Token for pagination to retrieve the next page of results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      [QueryParameter("pagination_token")]
      public string? PaginationToken { get; set; }
#nullable restore
#else
      [QueryParameter("pagination_token")]
      public string PaginationToken { get; set; }
#endif
    }
  }
}
#pragma warning restore CS0618
