// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using XbyOpenApi.Core.Client.Two.Chat.Media.Item;
using XbyOpenApi.Core.Client.Two.Chat.Media.Upload;
namespace XbyOpenApi.Core.Client.Two.Chat.Media
{
  /// <summary>
  /// Builds and executes requests for operations under \2\chat\media
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class MediaRequestBuilder : BaseRequestBuilder
  {
    /// <summary>The upload property</summary>
    public global::XbyOpenApi.Core.Client.Two.Chat.Media.Upload.UploadRequestBuilder Upload
    {
      get => new global::XbyOpenApi.Core.Client.Two.Chat.Media.Upload.UploadRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>Gets an item from the XbyOpenApi.Core.Client.Two.chat.media.item collection</summary>
    /// <param name="position">The recipient&apos;s user ID for a 1:1 conversation, or a group conversation ID (prefixed with &apos;g&apos;).</param>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Two.Chat.Media.Item.MediaItemRequestBuilder"/></returns>
    public global::XbyOpenApi.Core.Client.Two.Chat.Media.Item.MediaItemRequestBuilder this[string position]
    {
      get
      {
        var urlTplParams = new Dictionary<string, object>(PathParameters);
        urlTplParams.Add("id", position);
        return new global::XbyOpenApi.Core.Client.Two.Chat.Media.Item.MediaItemRequestBuilder(urlTplParams, RequestAdapter);
      }
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Chat.Media.MediaRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public MediaRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/chat/media", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Chat.Media.MediaRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public MediaRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/chat/media", rawUrl)
    {
    }
  }
}
#pragma warning restore CS0618
