// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591
  public partial class ActivitySubscriptionCreateRequest : IParsable
#pragma warning restore CS1591
  {
    /// <summary>The event_type property</summary>
    public global::XbyOpenApi.Core.Client.Models.ActivitySubscriptionCreateRequest_event_type? EventType { get; set; }
    /// <summary>An XAA subscription.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.ActivitySubscriptionFilter? Filter { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.ActivitySubscriptionFilter Filter { get; set; }
#endif
    /// <summary>The tag property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? Tag { get; set; }
#nullable restore
#else
    public string Tag { get; set; }
#endif
    /// <summary>The unique identifier of this webhook config.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? WebhookId { get; set; }
#nullable restore
#else
    public string WebhookId { get; set; }
#endif
    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.ActivitySubscriptionCreateRequest"/></returns>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static global::XbyOpenApi.Core.Client.Models.ActivitySubscriptionCreateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
    {
      if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
      return new global::XbyOpenApi.Core.Client.Models.ActivitySubscriptionCreateRequest();
    }
    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
    public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
      return new Dictionary<string, Action<IParseNode>>
            {
                { "event_type", n => { EventType = n.GetEnumValue<global::XbyOpenApi.Core.Client.Models.ActivitySubscriptionCreateRequest_event_type>(); } },
                { "filter", n => { Filter = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.ActivitySubscriptionFilter>(global::XbyOpenApi.Core.Client.Models.ActivitySubscriptionFilter.CreateFromDiscriminatorValue); } },
                { "tag", n => { Tag = n.GetStringValue(); } },
                { "webhook_id", n => { WebhookId = n.GetStringValue(); } },
            };
    }
    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public virtual void Serialize(ISerializationWriter writer)
    {
      if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
      writer.WriteEnumValue<global::XbyOpenApi.Core.Client.Models.ActivitySubscriptionCreateRequest_event_type>("event_type", EventType);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.ActivitySubscriptionFilter>("filter", Filter);
      writer.WriteStringValue("tag", Tag);
      writer.WriteStringValue("webhook_id", WebhookId);
    }
  }
}
#pragma warning restore CS0618
