// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  /// <summary>
  /// A response from modifying user-specified stream filtering rules.
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class AddOrDeleteRulesResponse : IAdditionalDataHolder, IParsable
  {
    /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
    public IDictionary<string, object> AdditionalData { get; set; }
    /// <summary>All user-specified stream filtering rules that were created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public List<global::XbyOpenApi.Core.Client.Models.Rule>? Data { get; set; }
#nullable restore
#else
    public List<global::XbyOpenApi.Core.Client.Models.Rule> Data { get; set; }
#endif
    /// <summary>The errors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public List<global::XbyOpenApi.Core.Client.Models.Problem>? Errors { get; set; }
#nullable restore
#else
    public List<global::XbyOpenApi.Core.Client.Models.Problem> Errors { get; set; }
#endif
    /// <summary>The meta property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.RulesResponseMetadata? Meta { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.RulesResponseMetadata Meta { get; set; }
#endif
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Models.AddOrDeleteRulesResponse"/> and sets the default values.
    /// </summary>
    public AddOrDeleteRulesResponse()
    {
      AdditionalData = new Dictionary<string, object>();
    }
    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.AddOrDeleteRulesResponse"/></returns>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static global::XbyOpenApi.Core.Client.Models.AddOrDeleteRulesResponse CreateFromDiscriminatorValue(IParseNode parseNode)
    {
      if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
      return new global::XbyOpenApi.Core.Client.Models.AddOrDeleteRulesResponse();
    }
    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
    public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
      return new Dictionary<string, Action<IParseNode>>
            {
                { "data", n => { Data = n.GetCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.Rule>(global::XbyOpenApi.Core.Client.Models.Rule.CreateFromDiscriminatorValue)?.AsList(); } },
                { "errors", n => { Errors = n.GetCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.Problem>(global::XbyOpenApi.Core.Client.Models.Problem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "meta", n => { Meta = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.RulesResponseMetadata>(global::XbyOpenApi.Core.Client.Models.RulesResponseMetadata.CreateFromDiscriminatorValue); } },
            };
    }
    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public virtual void Serialize(ISerializationWriter writer)
    {
      if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
      writer.WriteCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.Rule>("data", Data);
      writer.WriteCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.Problem>("errors", Errors);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.RulesResponseMetadata>("meta", Meta);
      writer.WriteAdditionalData(AdditionalData);
    }
  }
}
#pragma warning restore CS0618
