// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591
  public partial class CreateDmConversationRequest : IParsable
#pragma warning restore CS1591
  {
    /// <summary>The conversation type that is being created.</summary>
    public global::XbyOpenApi.Core.Client.Models.CreateDmConversationRequest_conversation_type? ConversationType { get; set; }
    /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.CreateMessageRequest? Message { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.CreateMessageRequest Message { get; set; }
#endif
    /// <summary>Participants for the DM Conversation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public List<string>? ParticipantIds { get; set; }
#nullable restore
#else
    public List<string> ParticipantIds { get; set; }
#endif
    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.CreateDmConversationRequest"/></returns>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static global::XbyOpenApi.Core.Client.Models.CreateDmConversationRequest CreateFromDiscriminatorValue(IParseNode parseNode)
    {
      if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
      return new global::XbyOpenApi.Core.Client.Models.CreateDmConversationRequest();
    }
    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
    public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
      return new Dictionary<string, Action<IParseNode>>
            {
                { "conversation_type", n => { ConversationType = n.GetEnumValue<global::XbyOpenApi.Core.Client.Models.CreateDmConversationRequest_conversation_type>(); } },
                { "message", n => { Message = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMessageRequest>(global::XbyOpenApi.Core.Client.Models.CreateMessageRequest.CreateFromDiscriminatorValue); } },
                { "participant_ids", n => { ParticipantIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
    }
    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public virtual void Serialize(ISerializationWriter writer)
    {
      if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
      writer.WriteEnumValue<global::XbyOpenApi.Core.Client.Models.CreateDmConversationRequest_conversation_type>("conversation_type", ConversationType);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMessageRequest>("message", Message);
      writer.WriteCollectionOfPrimitiveValues<string>("participant_ids", ParticipantIds);
    }
  }
}
#pragma warning restore CS0618
