// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591
  public partial class FullTextEntities : IAdditionalDataHolder, IParsable
#pragma warning restore CS1591
  {
    /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
    public IDictionary<string, object> AdditionalData { get; set; }
    /// <summary>The annotations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public List<global::XbyOpenApi.Core.Client.Models.FullTextEntities_annotations>? Annotations { get; set; }
#nullable restore
#else
    public List<global::XbyOpenApi.Core.Client.Models.FullTextEntities_annotations> Annotations { get; set; }
#endif
    /// <summary>The cashtags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public List<global::XbyOpenApi.Core.Client.Models.CashtagEntity>? Cashtags { get; set; }
#nullable restore
#else
    public List<global::XbyOpenApi.Core.Client.Models.CashtagEntity> Cashtags { get; set; }
#endif
    /// <summary>The hashtags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public List<global::XbyOpenApi.Core.Client.Models.HashtagEntity>? Hashtags { get; set; }
#nullable restore
#else
    public List<global::XbyOpenApi.Core.Client.Models.HashtagEntity> Hashtags { get; set; }
#endif
    /// <summary>The mentions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public List<global::XbyOpenApi.Core.Client.Models.MentionEntity>? Mentions { get; set; }
#nullable restore
#else
    public List<global::XbyOpenApi.Core.Client.Models.MentionEntity> Mentions { get; set; }
#endif
    /// <summary>The urls property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public List<global::XbyOpenApi.Core.Client.Models.UrlEntity>? Urls { get; set; }
#nullable restore
#else
    public List<global::XbyOpenApi.Core.Client.Models.UrlEntity> Urls { get; set; }
#endif
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Models.FullTextEntities"/> and sets the default values.
    /// </summary>
    public FullTextEntities()
    {
      AdditionalData = new Dictionary<string, object>();
    }
    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.FullTextEntities"/></returns>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static global::XbyOpenApi.Core.Client.Models.FullTextEntities CreateFromDiscriminatorValue(IParseNode parseNode)
    {
      if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
      return new global::XbyOpenApi.Core.Client.Models.FullTextEntities();
    }
    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
    public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
      return new Dictionary<string, Action<IParseNode>>
            {
                { "annotations", n => { Annotations = n.GetCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.FullTextEntities_annotations>(global::XbyOpenApi.Core.Client.Models.FullTextEntities_annotations.CreateFromDiscriminatorValue)?.AsList(); } },
                { "cashtags", n => { Cashtags = n.GetCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.CashtagEntity>(global::XbyOpenApi.Core.Client.Models.CashtagEntity.CreateFromDiscriminatorValue)?.AsList(); } },
                { "hashtags", n => { Hashtags = n.GetCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.HashtagEntity>(global::XbyOpenApi.Core.Client.Models.HashtagEntity.CreateFromDiscriminatorValue)?.AsList(); } },
                { "mentions", n => { Mentions = n.GetCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.MentionEntity>(global::XbyOpenApi.Core.Client.Models.MentionEntity.CreateFromDiscriminatorValue)?.AsList(); } },
                { "urls", n => { Urls = n.GetCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.UrlEntity>(global::XbyOpenApi.Core.Client.Models.UrlEntity.CreateFromDiscriminatorValue)?.AsList(); } },
            };
    }
    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public virtual void Serialize(ISerializationWriter writer)
    {
      if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
      writer.WriteCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.FullTextEntities_annotations>("annotations", Annotations);
      writer.WriteCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.CashtagEntity>("cashtags", Cashtags);
      writer.WriteCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.HashtagEntity>("hashtags", Hashtags);
      writer.WriteCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.MentionEntity>("mentions", Mentions);
      writer.WriteCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.UrlEntity>("urls", Urls);
      writer.WriteAdditionalData(AdditionalData);
    }
  }
}
#pragma warning restore CS0618
