// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  /// <summary>
  /// Composed type wrapper for classes <see cref="global::XbyOpenApi.Core.Client.Models.MediaUploadAppendRequestMember1"/>, <see cref="global::XbyOpenApi.Core.Client.Models.MediaUploadAppendRequestMember2"/>
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class MediaUploadAppendRequest : IComposedTypeWrapper, IParsable
  {
    /// <summary>Composed type representation for type <see cref="global::XbyOpenApi.Core.Client.Models.MediaUploadAppendRequestMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.MediaUploadAppendRequestMember1? MediaUploadAppendRequestMember1 { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.MediaUploadAppendRequestMember1 MediaUploadAppendRequestMember1 { get; set; }
#endif
    /// <summary>Composed type representation for type <see cref="global::XbyOpenApi.Core.Client.Models.MediaUploadAppendRequestMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.MediaUploadAppendRequestMember2? MediaUploadAppendRequestMember2 { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.MediaUploadAppendRequestMember2 MediaUploadAppendRequestMember2 { get; set; }
#endif
    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.MediaUploadAppendRequest"/></returns>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static global::XbyOpenApi.Core.Client.Models.MediaUploadAppendRequest CreateFromDiscriminatorValue(IParseNode parseNode)
    {
      if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
      var result = new global::XbyOpenApi.Core.Client.Models.MediaUploadAppendRequest();
      result.MediaUploadAppendRequestMember1 = new global::XbyOpenApi.Core.Client.Models.MediaUploadAppendRequestMember1();
      result.MediaUploadAppendRequestMember2 = new global::XbyOpenApi.Core.Client.Models.MediaUploadAppendRequestMember2();
      return result;
    }
    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
    public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
      if (MediaUploadAppendRequestMember1 != null || MediaUploadAppendRequestMember2 != null)
      {
        return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(MediaUploadAppendRequestMember1, MediaUploadAppendRequestMember2);
      }
      return new Dictionary<string, Action<IParseNode>>();
    }
    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public virtual void Serialize(ISerializationWriter writer)
    {
      if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.MediaUploadAppendRequestMember1>(null, MediaUploadAppendRequestMember1, MediaUploadAppendRequestMember2);
    }
  }
}
#pragma warning restore CS0618
