// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  /// <summary>
  /// A X Community Note is a note on a Post.
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class Note : IAdditionalDataHolder, IParsable
  {
    /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
    public IDictionary<string, object> AdditionalData { get; set; }
    /// <summary>The unique identifier of this Community Note.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? Id { get; set; }
#nullable restore
#else
    public string Id { get; set; }
#endif
    /// <summary>A X Community Note is a note on a Post.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.NoteInfo? Info { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.NoteInfo Info { get; set; }
#endif
    /// <summary>Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? PostId { get; set; }
#nullable restore
#else
    public string PostId { get; set; }
#endif
    /// <summary>Community Note rating status</summary>
    public global::XbyOpenApi.Core.Client.Models.NoteRatingStatus? Status { get; set; }
    /// <summary>The evaluation result of a community note.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.NoteTestResult? TestResult { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.NoteTestResult TestResult { get; set; }
#endif
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Models.Note"/> and sets the default values.
    /// </summary>
    public Note()
    {
      AdditionalData = new Dictionary<string, object>();
    }
    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.Note"/></returns>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static global::XbyOpenApi.Core.Client.Models.Note CreateFromDiscriminatorValue(IParseNode parseNode)
    {
      if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
      return new global::XbyOpenApi.Core.Client.Models.Note();
    }
    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
    public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
      return new Dictionary<string, Action<IParseNode>>
            {
                { "id", n => { Id = n.GetStringValue(); } },
                { "info", n => { Info = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.NoteInfo>(global::XbyOpenApi.Core.Client.Models.NoteInfo.CreateFromDiscriminatorValue); } },
                { "post_id", n => { PostId = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::XbyOpenApi.Core.Client.Models.NoteRatingStatus>(); } },
                { "test_result", n => { TestResult = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.NoteTestResult>(global::XbyOpenApi.Core.Client.Models.NoteTestResult.CreateFromDiscriminatorValue); } },
            };
    }
    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public virtual void Serialize(ISerializationWriter writer)
    {
      if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
      writer.WriteStringValue("id", Id);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.NoteInfo>("info", Info);
      writer.WriteStringValue("post_id", PostId);
      writer.WriteEnumValue<global::XbyOpenApi.Core.Client.Models.NoteRatingStatus>("status", Status);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.NoteTestResult>("test_result", TestResult);
      writer.WriteAdditionalData(AdditionalData);
    }
  }
}
#pragma warning restore CS0618
