// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using XbyOpenApi.Core.Client.Models;
using XbyOpenApi.Core.Client.Two.Activity.Subscriptions.Item;
namespace XbyOpenApi.Core.Client.Two.Activity.Subscriptions
{
  /// <summary>
  /// Builds and executes requests for operations under \2\activity\subscriptions
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class SubscriptionsRequestBuilder : BaseRequestBuilder
  {
    /// <summary>Gets an item from the XbyOpenApi.Core.Client.Two.activity.subscriptions.item collection</summary>
    /// <param name="position">The ID of the subscription to delete.</param>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Two.Activity.Subscriptions.Item.WithSubscription_ItemRequestBuilder"/></returns>
    public global::XbyOpenApi.Core.Client.Two.Activity.Subscriptions.Item.WithSubscription_ItemRequestBuilder this[string position]
    {
      get
      {
        var urlTplParams = new Dictionary<string, object>(PathParameters);
        urlTplParams.Add("subscription_id", position);
        return new global::XbyOpenApi.Core.Client.Two.Activity.Subscriptions.Item.WithSubscription_ItemRequestBuilder(urlTplParams, RequestAdapter);
      }
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Activity.Subscriptions.SubscriptionsRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public SubscriptionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/activity/subscriptions", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Activity.Subscriptions.SubscriptionsRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public SubscriptionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/activity/subscriptions", rawUrl)
    {
    }
    /// <summary>
    /// Get a list of active subscriptions for XAA
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.ActivitySubscriptionGetResponse"/></returns>
    /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
    /// <exception cref="global::XbyOpenApi.Core.Client.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public async Task<global::XbyOpenApi.Core.Client.Models.ActivitySubscriptionGetResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#nullable restore
#else
    public async Task<global::XbyOpenApi.Core.Client.Models.ActivitySubscriptionGetResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#endif
      var requestInfo = ToGetRequestInformation(requestConfiguration);
      var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::XbyOpenApi.Core.Client.Models.Error.CreateFromDiscriminatorValue },
            };
      return await RequestAdapter.SendAsync<global::XbyOpenApi.Core.Client.Models.ActivitySubscriptionGetResponse>(requestInfo, global::XbyOpenApi.Core.Client.Models.ActivitySubscriptionGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
    }
    /// <summary>
    /// Creates a subscription for an X activity event
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.ActivitySubscriptionCreateResponse"/></returns>
    /// <param name="body">The request body</param>
    /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
    /// <exception cref="global::XbyOpenApi.Core.Client.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public async Task<global::XbyOpenApi.Core.Client.Models.ActivitySubscriptionCreateResponse?> PostAsync(global::XbyOpenApi.Core.Client.Models.ActivitySubscriptionCreateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#nullable restore
#else
    public async Task<global::XbyOpenApi.Core.Client.Models.ActivitySubscriptionCreateResponse> PostAsync(global::XbyOpenApi.Core.Client.Models.ActivitySubscriptionCreateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#endif
      if (ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
      var requestInfo = ToPostRequestInformation(body, requestConfiguration);
      var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::XbyOpenApi.Core.Client.Models.Error.CreateFromDiscriminatorValue },
            };
      return await RequestAdapter.SendAsync<global::XbyOpenApi.Core.Client.Models.ActivitySubscriptionCreateResponse>(requestInfo, global::XbyOpenApi.Core.Client.Models.ActivitySubscriptionCreateResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
    }
    /// <summary>
    /// Get a list of active subscriptions for XAA
    /// </summary>
    /// <returns>A <see cref="RequestInformation"/></returns>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
    {
#nullable restore
#else
    public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
    {
#endif
      var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
      requestInfo.Configure(requestConfiguration);
      requestInfo.Headers.TryAdd("Accept", "application/json");
      return requestInfo;
    }
    /// <summary>
    /// Creates a subscription for an X activity event
    /// </summary>
    /// <returns>A <see cref="RequestInformation"/></returns>
    /// <param name="body">The request body</param>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public RequestInformation ToPostRequestInformation(global::XbyOpenApi.Core.Client.Models.ActivitySubscriptionCreateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
    {
#nullable restore
#else
    public RequestInformation ToPostRequestInformation(global::XbyOpenApi.Core.Client.Models.ActivitySubscriptionCreateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
    {
#endif
      if (ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
      var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
      requestInfo.Configure(requestConfiguration);
      requestInfo.Headers.TryAdd("Accept", "application/json");
      requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
      return requestInfo;
    }
    /// <summary>
    /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Two.Activity.Subscriptions.SubscriptionsRequestBuilder"/></returns>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    public global::XbyOpenApi.Core.Client.Two.Activity.Subscriptions.SubscriptionsRequestBuilder WithUrl(string rawUrl)
    {
      return new global::XbyOpenApi.Core.Client.Two.Activity.Subscriptions.SubscriptionsRequestBuilder(rawUrl, RequestAdapter);
    }
  }
}
#pragma warning restore CS0618
