// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using XbyOpenApi.Core.Client.Models;
using XbyOpenApi.Core.Client.Two.Lists.Item.Followers;
using XbyOpenApi.Core.Client.Two.Lists.Item.Members;
using XbyOpenApi.Core.Client.Two.Lists.Item.Tweets;
namespace XbyOpenApi.Core.Client.Two.Lists.Item
{
  /// <summary>
  /// Builds and executes requests for operations under \2\lists\{id}
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class ListsItemRequestBuilder : BaseRequestBuilder
  {
    /// <summary>The followers property</summary>
    public global::XbyOpenApi.Core.Client.Two.Lists.Item.Followers.FollowersRequestBuilder Followers
    {
      get => new global::XbyOpenApi.Core.Client.Two.Lists.Item.Followers.FollowersRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The members property</summary>
    public global::XbyOpenApi.Core.Client.Two.Lists.Item.Members.MembersRequestBuilder Members
    {
      get => new global::XbyOpenApi.Core.Client.Two.Lists.Item.Members.MembersRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The tweets property</summary>
    public global::XbyOpenApi.Core.Client.Two.Lists.Item.Tweets.TweetsRequestBuilder Tweets
    {
      get => new global::XbyOpenApi.Core.Client.Two.Lists.Item.Tweets.TweetsRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Lists.Item.ListsItemRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public ListsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/lists/{id}{?expansions,list%2Efields,user%2Efields}", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Lists.Item.ListsItemRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public ListsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/lists/{id}{?expansions,list%2Efields,user%2Efields}", rawUrl)
    {
    }
    /// <summary>
    /// Deletes a specific List owned by the authenticated user by its ID.
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.ListDeleteResponse"/></returns>
    /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
    /// <exception cref="global::XbyOpenApi.Core.Client.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public async Task<global::XbyOpenApi.Core.Client.Models.ListDeleteResponse?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#nullable restore
#else
    public async Task<global::XbyOpenApi.Core.Client.Models.ListDeleteResponse> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#endif
      var requestInfo = ToDeleteRequestInformation(requestConfiguration);
      var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::XbyOpenApi.Core.Client.Models.Error.CreateFromDiscriminatorValue },
            };
      return await RequestAdapter.SendAsync<global::XbyOpenApi.Core.Client.Models.ListDeleteResponse>(requestInfo, global::XbyOpenApi.Core.Client.Models.ListDeleteResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
    }
    /// <summary>
    /// Retrieves details of a specific List by its ID.
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.Get2ListsIdResponse"/></returns>
    /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
    /// <exception cref="global::XbyOpenApi.Core.Client.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public async Task<global::XbyOpenApi.Core.Client.Models.Get2ListsIdResponse?> GetAsync(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Lists.Item.ListsItemRequestBuilder.ListsItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#nullable restore
#else
    public async Task<global::XbyOpenApi.Core.Client.Models.Get2ListsIdResponse> GetAsync(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Lists.Item.ListsItemRequestBuilder.ListsItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#endif
      var requestInfo = ToGetRequestInformation(requestConfiguration);
      var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::XbyOpenApi.Core.Client.Models.Error.CreateFromDiscriminatorValue },
            };
      return await RequestAdapter.SendAsync<global::XbyOpenApi.Core.Client.Models.Get2ListsIdResponse>(requestInfo, global::XbyOpenApi.Core.Client.Models.Get2ListsIdResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
    }
    /// <summary>
    /// Updates the details of a specific List owned by the authenticated user by its ID.
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.ListUpdateResponse"/></returns>
    /// <param name="body">The request body</param>
    /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
    /// <exception cref="global::XbyOpenApi.Core.Client.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public async Task<global::XbyOpenApi.Core.Client.Models.ListUpdateResponse?> PutAsync(global::XbyOpenApi.Core.Client.Models.ListUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#nullable restore
#else
    public async Task<global::XbyOpenApi.Core.Client.Models.ListUpdateResponse> PutAsync(global::XbyOpenApi.Core.Client.Models.ListUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#endif
      if (ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
      var requestInfo = ToPutRequestInformation(body, requestConfiguration);
      var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::XbyOpenApi.Core.Client.Models.Error.CreateFromDiscriminatorValue },
            };
      return await RequestAdapter.SendAsync<global::XbyOpenApi.Core.Client.Models.ListUpdateResponse>(requestInfo, global::XbyOpenApi.Core.Client.Models.ListUpdateResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
    }
    /// <summary>
    /// Deletes a specific List owned by the authenticated user by its ID.
    /// </summary>
    /// <returns>A <see cref="RequestInformation"/></returns>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
    {
#nullable restore
#else
    public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
    {
#endif
      var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
      requestInfo.Configure(requestConfiguration);
      requestInfo.Headers.TryAdd("Accept", "application/json");
      return requestInfo;
    }
    /// <summary>
    /// Retrieves details of a specific List by its ID.
    /// </summary>
    /// <returns>A <see cref="RequestInformation"/></returns>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Lists.Item.ListsItemRequestBuilder.ListsItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
    {
#nullable restore
#else
    public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Lists.Item.ListsItemRequestBuilder.ListsItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
    {
#endif
      var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
      requestInfo.Configure(requestConfiguration);
      requestInfo.Headers.TryAdd("Accept", "application/json");
      return requestInfo;
    }
    /// <summary>
    /// Updates the details of a specific List owned by the authenticated user by its ID.
    /// </summary>
    /// <returns>A <see cref="RequestInformation"/></returns>
    /// <param name="body">The request body</param>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public RequestInformation ToPutRequestInformation(global::XbyOpenApi.Core.Client.Models.ListUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
    {
#nullable restore
#else
    public RequestInformation ToPutRequestInformation(global::XbyOpenApi.Core.Client.Models.ListUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
    {
#endif
      if (ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
      var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
      requestInfo.Configure(requestConfiguration);
      requestInfo.Headers.TryAdd("Accept", "application/json");
      requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
      return requestInfo;
    }
    /// <summary>
    /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Two.Lists.Item.ListsItemRequestBuilder"/></returns>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    public global::XbyOpenApi.Core.Client.Two.Lists.Item.ListsItemRequestBuilder WithUrl(string rawUrl)
    {
      return new global::XbyOpenApi.Core.Client.Two.Lists.Item.ListsItemRequestBuilder(rawUrl, RequestAdapter);
    }
    /// <summary>
    /// Retrieves details of a specific List by its ID.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListsItemRequestBuilderGetQueryParameters
    {
      /// <summary>A comma separated list of fields to expand.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      [QueryParameter("expansions")]
      public global::XbyOpenApi.Core.Client.Two.Lists.Item.GetExpansionsQueryParameterType[]? Expansions { get; set; }
#nullable restore
#else
      [QueryParameter("expansions")]
      public global::XbyOpenApi.Core.Client.Two.Lists.Item.GetExpansionsQueryParameterType[] Expansions { get; set; }
#endif
      /// <summary>A comma separated list of List fields to display.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      [QueryParameter("list%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Lists.Item.GetListFieldsQueryParameterType[]? ListFields { get; set; }
#nullable restore
#else
      [QueryParameter("list%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Lists.Item.GetListFieldsQueryParameterType[] ListFields { get; set; }
#endif
      /// <summary>A comma separated list of User fields to display.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      [QueryParameter("user%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Lists.Item.GetUserFieldsQueryParameterType[]? UserFields { get; set; }
#nullable restore
#else
      [QueryParameter("user%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Lists.Item.GetUserFieldsQueryParameterType[] UserFields { get; set; }
#endif
    }
  }
}
#pragma warning restore CS0618
