// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using XbyOpenApi.Core.Client.Models;
using XbyOpenApi.Core.Client.Two.Tweets.Item.Hidden;
using XbyOpenApi.Core.Client.Two.Tweets.Item.Liking_users;
using XbyOpenApi.Core.Client.Two.Tweets.Item.Quote_tweets;
using XbyOpenApi.Core.Client.Two.Tweets.Item.Retweeted_by;
using XbyOpenApi.Core.Client.Two.Tweets.Item.Retweets;
namespace XbyOpenApi.Core.Client.Two.Tweets.Item
{
  /// <summary>
  /// Builds and executes requests for operations under \2\tweets\{-id}
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class ItemRequestBuilder : BaseRequestBuilder
  {
    /// <summary>The hidden property</summary>
    public global::XbyOpenApi.Core.Client.Two.Tweets.Item.Hidden.HiddenRequestBuilder Hidden
    {
      get => new global::XbyOpenApi.Core.Client.Two.Tweets.Item.Hidden.HiddenRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The liking_users property</summary>
    public global::XbyOpenApi.Core.Client.Two.Tweets.Item.Liking_users.Liking_usersRequestBuilder Liking_users
    {
      get => new global::XbyOpenApi.Core.Client.Two.Tweets.Item.Liking_users.Liking_usersRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The quote_tweets property</summary>
    public global::XbyOpenApi.Core.Client.Two.Tweets.Item.Quote_tweets.Quote_tweetsRequestBuilder Quote_tweets
    {
      get => new global::XbyOpenApi.Core.Client.Two.Tweets.Item.Quote_tweets.Quote_tweetsRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The retweeted_by property</summary>
    public global::XbyOpenApi.Core.Client.Two.Tweets.Item.Retweeted_by.Retweeted_byRequestBuilder Retweeted_by
    {
      get => new global::XbyOpenApi.Core.Client.Two.Tweets.Item.Retweeted_by.Retweeted_byRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The retweets property</summary>
    public global::XbyOpenApi.Core.Client.Two.Tweets.Item.Retweets.RetweetsRequestBuilder Retweets
    {
      get => new global::XbyOpenApi.Core.Client.Two.Tweets.Item.Retweets.RetweetsRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Tweets.Item.ItemRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/tweets/{%2Did}{?expansions,media%2Efields,place%2Efields,poll%2Efields,tweet%2Efields,user%2Efields}", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Tweets.Item.ItemRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/tweets/{%2Did}{?expansions,media%2Efields,place%2Efields,poll%2Efields,tweet%2Efields,user%2Efields}", rawUrl)
    {
    }
    /// <summary>
    /// Deletes a specific Post by its ID, if owned by the authenticated user.
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.TweetDeleteResponse"/></returns>
    /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
    /// <exception cref="global::XbyOpenApi.Core.Client.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public async Task<global::XbyOpenApi.Core.Client.Models.TweetDeleteResponse?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#nullable restore
#else
    public async Task<global::XbyOpenApi.Core.Client.Models.TweetDeleteResponse> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#endif
      var requestInfo = ToDeleteRequestInformation(requestConfiguration);
      var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::XbyOpenApi.Core.Client.Models.Error.CreateFromDiscriminatorValue },
            };
      return await RequestAdapter.SendAsync<global::XbyOpenApi.Core.Client.Models.TweetDeleteResponse>(requestInfo, global::XbyOpenApi.Core.Client.Models.TweetDeleteResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
    }
    /// <summary>
    /// Retrieves details of a specific Post by its ID.
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.Get2TweetsIdResponse"/></returns>
    /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
    /// <exception cref="global::XbyOpenApi.Core.Client.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public async Task<global::XbyOpenApi.Core.Client.Models.Get2TweetsIdResponse?> GetAsync(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Tweets.Item.ItemRequestBuilder.ItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#nullable restore
#else
    public async Task<global::XbyOpenApi.Core.Client.Models.Get2TweetsIdResponse> GetAsync(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Tweets.Item.ItemRequestBuilder.ItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#endif
      var requestInfo = ToGetRequestInformation(requestConfiguration);
      var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::XbyOpenApi.Core.Client.Models.Error.CreateFromDiscriminatorValue },
            };
      return await RequestAdapter.SendAsync<global::XbyOpenApi.Core.Client.Models.Get2TweetsIdResponse>(requestInfo, global::XbyOpenApi.Core.Client.Models.Get2TweetsIdResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
    }
    /// <summary>
    /// Deletes a specific Post by its ID, if owned by the authenticated user.
    /// </summary>
    /// <returns>A <see cref="RequestInformation"/></returns>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
    {
#nullable restore
#else
    public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
    {
#endif
      var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
      requestInfo.Configure(requestConfiguration);
      requestInfo.Headers.TryAdd("Accept", "application/json");
      return requestInfo;
    }
    /// <summary>
    /// Retrieves details of a specific Post by its ID.
    /// </summary>
    /// <returns>A <see cref="RequestInformation"/></returns>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Tweets.Item.ItemRequestBuilder.ItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
    {
#nullable restore
#else
    public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Tweets.Item.ItemRequestBuilder.ItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
    {
#endif
      var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
      requestInfo.Configure(requestConfiguration);
      requestInfo.Headers.TryAdd("Accept", "application/json");
      return requestInfo;
    }
    /// <summary>
    /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Two.Tweets.Item.ItemRequestBuilder"/></returns>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    public global::XbyOpenApi.Core.Client.Two.Tweets.Item.ItemRequestBuilder WithUrl(string rawUrl)
    {
      return new global::XbyOpenApi.Core.Client.Two.Tweets.Item.ItemRequestBuilder(rawUrl, RequestAdapter);
    }
    /// <summary>
    /// Retrieves details of a specific Post by its ID.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ItemRequestBuilderGetQueryParameters
    {
      /// <summary>A comma separated list of fields to expand.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      [QueryParameter("expansions")]
      public global::XbyOpenApi.Core.Client.Two.Tweets.Item.GetExpansionsQueryParameterType[]? Expansions { get; set; }
#nullable restore
#else
      [QueryParameter("expansions")]
      public global::XbyOpenApi.Core.Client.Two.Tweets.Item.GetExpansionsQueryParameterType[] Expansions { get; set; }
#endif
      /// <summary>A comma separated list of Media fields to display.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      [QueryParameter("media%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Tweets.Item.GetMediaFieldsQueryParameterType[]? MediaFields { get; set; }
#nullable restore
#else
      [QueryParameter("media%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Tweets.Item.GetMediaFieldsQueryParameterType[] MediaFields { get; set; }
#endif
      /// <summary>A comma separated list of Place fields to display.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      [QueryParameter("place%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Tweets.Item.GetPlaceFieldsQueryParameterType[]? PlaceFields { get; set; }
#nullable restore
#else
      [QueryParameter("place%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Tweets.Item.GetPlaceFieldsQueryParameterType[] PlaceFields { get; set; }
#endif
      /// <summary>A comma separated list of Poll fields to display.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      [QueryParameter("poll%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Tweets.Item.GetPollFieldsQueryParameterType[]? PollFields { get; set; }
#nullable restore
#else
      [QueryParameter("poll%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Tweets.Item.GetPollFieldsQueryParameterType[] PollFields { get; set; }
#endif
      /// <summary>A comma separated list of Tweet fields to display.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      [QueryParameter("tweet%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Tweets.Item.GetTweetFieldsQueryParameterType[]? TweetFields { get; set; }
#nullable restore
#else
      [QueryParameter("tweet%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Tweets.Item.GetTweetFieldsQueryParameterType[] TweetFields { get; set; }
#endif
      /// <summary>A comma separated list of User fields to display.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      [QueryParameter("user%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Tweets.Item.GetUserFieldsQueryParameterType[]? UserFields { get; set; }
#nullable restore
#else
      [QueryParameter("user%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Tweets.Item.GetUserFieldsQueryParameterType[] UserFields { get; set; }
#endif
    }
  }
}
#pragma warning restore CS0618
