// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using XbyOpenApi.Core.Client.Two.Chat.Conversations;
using XbyOpenApi.Core.Client.Two.Chat.Media;
namespace XbyOpenApi.Core.Client.Two.Chat
{
  /// <summary>
  /// Builds and executes requests for operations under \2\chat
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class ChatRequestBuilder : BaseRequestBuilder
  {
    /// <summary>The conversations property</summary>
    public global::XbyOpenApi.Core.Client.Two.Chat.Conversations.ConversationsRequestBuilder Conversations
    {
      get => new global::XbyOpenApi.Core.Client.Two.Chat.Conversations.ConversationsRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The media property</summary>
    public global::XbyOpenApi.Core.Client.Two.Chat.Media.MediaRequestBuilder Media
    {
      get => new global::XbyOpenApi.Core.Client.Two.Chat.Media.MediaRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Chat.ChatRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public ChatRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/chat", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Chat.ChatRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public ChatRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/chat", rawUrl)
    {
    }
  }
}
#pragma warning restore CS0618
